requirements: fix pendulum install error
Because of: Building wheel for pendulum (PEP 517): started
  Building wheel for pendulum (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp6ivojlyl
       cwd: /tmp/pip-install-n_958gti/pendulum
  Complete output (24 lines):
  Traceback (most recent call last):
    File "setup.py", line 2, in <module>
      from setuptools import setup
  ModuleNotFoundError: No module named 'setuptools'

Change-Id: Ied8f3307fbaf70749d3a0d9822376bbf1507fc30
Signed-off-by: Angga <angga@linuxmail.org>